name: boticario
description: Boticário Prova

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypt: ^3.0.1
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  bot_toast: ^3.0.4
  curved_navigation_bar: ^0.3.4
  dio: ^3.0.10
  email_validator: ^1.0.6
  flutter_animator: ^2.1.0
  flutter_icons: ^1.1.0
  flutter_modular: ^2.0.1
  flutter_progress_button: ^1.0.0
  get: ^3.15.0
  intl: ^0.16.1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+2
  sqflite: ^1.3.1+2
dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/app/assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/app/assets/boticarioLogo.png"